tests: link settings_test_fs with kernel
pabigot/zephyr pull request #3
Opened 2021-01-21 09:42 UTC by tejlmand

This is patch to #29618 to specifically link settings_test_fs with
kernel library.

This is needed because Zephyr libraries created after
`find_package(Zephyr)` are not pure Zephyr libraries, as they are not
in the `whole-archive` linking grouping.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

2021-01-21 11:34 UTC, pabigot requested changes
Thank you, that's the trick I didn't know to try.

Looks good, but please remove this from the commit message:

    This is patch to #29618 to specifically link settings_test_fs with
    kernel library.

It doesn't seem useful to have that in the permanent record.  Or I can remove it and merge by hand, your choice.

2021-01-21 11:47 UTC, merged

2021-01-22 08:24 UTC, tejlmand commented
I wasn't sure how you wanted to take in the patch.
As-is or squash into earlier commit, so I just made the description according to what I fixed ;)
So always feel free to adjust, as you find fit.

2021-01-22 12:29 UTC, pabigot commented
> So always feel free to adjust, as you find fit.

Thanks; I'll keep that in mind going forward.  I don't merge PRs submitted on github because it screws up the way I manage branches locally; it's easier to fetch from another repository and cherry-pick. So you can always just push a branch and directly or in a comment send me a link to it, e.g. https://github.com/tejlmand/zephyr/tree/reviews/29618_proposal.

2021-01-22 13:25 UTC, tejlmand commented
will remember.
There are many different ways of handling suggestions/fixes, and you can still cherry-pick the commit directly from the branch, no need for merging the PR, if it doesn't fit your workflow.